version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "8082:8082"
    networks:
      - app-network
    depends_on:
      - clienttwo

  clienttwo:
    build:
      context: ./clientTwo
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
